# Generated by Django 4.2.6 on 2023-10-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfectioneryFactoryproduct2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
